ALTER  PROC BRUTE_FORCE_DETECTION
AS

CREATE TABLE #LOG (LOGDATE DATETIME, PROCESSINFO VARCHAR(100), TEXT VARCHAR(MAX));
INSERT INTO #LOG EXEC XP_READERRORLOG;

DECLARE @IP AS VARCHAR(100);
DECLARE @BEGDATE AS DATETIME;
DECLARE @ENDDATE AS DATETIME;
DECLARE @COUNT AS INT;
DECLARE @TEXT AS VARCHAR(max)='';
DECLARE @MSG AS VARCHAR(1000)='';

SELECT @COUNT=COUNT(*), @BEGDATE=MIN(LOGDATE),@ENDDATE=MAX(LOGDATE),@TEXT=TEXT FROM #LOG
WHERE TEXT LIKE 'Login failed%' AND LOGDATE>=DATEADD(MINUTE,-1,GETDATE())
GROUP BY TEXT
HAVING COUNT(LOGDATE)>100;

DECLARE @SEQ AS INT;

SELECT @SEQ=SEQ FROM master.dbo.SplitWithSeq(@TEXT,' ')
WHERE items ='[CLIENT:';

SELECT @IP=items FROM master.dbo.SplitWithSeq(@TEXT,' ') 
WHERE SEQ=@SEQ+1
SET @IP=REPLACE(@IP,']','');

SET @MSG='YOUR SYSTEM IS UNDER ATTACK! A MACHINE WITH IP ';
SET @MSG=@MSG + @IP;
SET @MSG=@MSG + ' HAS TRIED '+CONVERT(VARCHAR,@COUNT)+' WRONG PASSWORD BETWEEN ';
SET @MSG=@MSG + CONVERT(VARCHAR,@BEGDATE,108) +' AND '+ CONVERT(VARCHAR,@ENDDATE,108);

SELECT @MSG;

IF @COUNT>100
BEGIN
INSERT INTO AUDIT.dbo.BRUTE_FORCE_ATTACK ([COMPUTERIP], [DATE_], [BEGDATE], [ENDDATE], [COUNT_])
VALUES (@IP,GETDATE(),@BEGDATE,@ENDDATE,@COUNT);

EXEC msdb.dbo.sp_send_dbmail  
    @profile_name = 'SQLMAIL',  
    @recipients = 'sqlservermirk034@gmail.com',  
    @body= @msg,
    @subject = 'Brute Force Attack Detected';

	END
	
	DROP TABLE #LOG;


