CREATE TRIGGER MODIFY_DATABASE
ON ALL SERVER
FOR CREATE_DATABASE, DROP_DATABASE, ALTER_DATABASE
AS
BEGIN
DECLARE @MSG AS VARCHAR(1000)

SET @MSG='A DATABASE MODIFY ALERT! IP:'+CONVERT(VARCHAR,CONNECTIONPROPERTY('client_net_address'));
SET @MSG=@MSG+' APPLICATION NAME:'+PROGRAM_NAME();
SET @MSG=@MSG+' USERNAME:'+SUSER_NAME();
SET @MSG=@MSG+EVENTDATA().value('(/EVENT_INSTANCE/TSQLCommand/CommandText)[1]','nvarchar(1000)');

EXEC msdb.dbo.sp_send_dbmail
@profile_name='SQLMAIL',
@recipients='sqlservermirk034@gmail.com',
@body=@MSG,
@subject='SOMEONE IS TRYING TO MODIFY DATABASE!';
END