CREATE TRIGGER SA_ALLOWED_CONTROL
ON ALL SERVER
FOR LOGON
AS
BEGIN

IF SUSER_NAME()='SA'
BEGIN
	DECLARE @COUNT AS INT;
	SELECT @COUNT=COUNT(*) FROM AUDIT.dbo.ALLOWEDCOMPUTER
	WHERE IPADDRESS=CONNECTIONPROPERTY('client_net_address') AND PROGRAMNAME=PROGRAM_NAME()

	IF ISNULL(@COUNT,0)=0

		DECLARE @MSG AS VARCHAR(1000);
		SET @MSG='UNAUTHORIZED ENTRY DETECTED!';
		SET @MSG=@MSG+' IPA ADDRESS:'+CONVERT(VARCHAR,CONNECTIONPROPERTY('client_net_address'));
		SET @MSG=@MSG+' APPLICATION NAME: '+PROGRAM_NAME();
		
						EXEC msdb.dbo.sp_send_dbmail
						@profile_name='SQLMAIL',
						@recipients='sqlservermirk034@gmail.com',
						@body=@MSG,
						@subject='UNAUTHORIZED ENTRY DETECTED!';
END
END