CREATE TRIGGER MODIFY_DATABASE2
ON ALL SERVER
FOR CREATE_DATABASE, DROP_DATABASE, ALTER_DATABASE
AS
BEGIN

DECLARE @COUNT AS INT;
SELECT @COUNT=COUNT(*) FROM AUDIT.dbo.WHITELIST 
WHERE IPADDRESS IN (CONNECTIONPROPERTY('client_net_address'));
IF ISNULL(@COUNT,0)=0
BEGIN
	 ROLLBACK
END
END